### ISSUE TITLE
Example from LDOW2015 stopped working (missing component registration?)

### ISSUE THREAD

**Issue by jakubklimek** [ldvm/LDVMi#68]
When I upload these three files from the <a href="http://events.linkeddata.org/ldow2015/papers/ldow2015_paper_08.pdf">paper</a>:
http://opendata.cz/ldvm/ovm-vocab.ttl
https://raw.githubusercontent.com/payola/ldvm/master/rdf/examples/ovm-obce-links.ttl
http://opendata.cz/ldvm/ovm.ttl
I only see a Concept Visualiser (http://live.payola.cz:29080/pipelines#/list?discoveryId=298), not the pipeline from the paper.

**Comment by jakubklimek** [comment]
Actually, I forgot to switch on "combine with other data sources". However, when I switched it on now,it takes forever (maybe too many datasources to combine with?)

**Comment by jirihelmich** [comment]
Yep. That will be solved by adding the persistent flag and cleanup of
permanent. At least for a while.

In the version we spoke about today, it should probably also be on per user
basis and/or allow for discovery flag. To narrow down the number of
possible branches since this is the base for the 1st iteration...
Wed, 21 Oct 2015 v 16:53 odesílatel Jakub Klímek <notifications@github.com>
napsal:

**Comment by jirihelmich** [comment]
Fixed by closing #79.
